language: node_js
node_js:
- '10'

script: npm run build

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
  - provider: script
    script: bash server/deploy.sh
    on:
      branch: master
