language: node_js
node_js:
- '10'
script: npm run build
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master
env:
  global:
    secure: UhBj9wKiveuxJZbVKfwtpZvKPnWGAcvq+oCq9C2mjhx6Wa6XtPuxEO/pfNJgcAxwbDwr2Xtpt4HWWIXeFMGPrZ/WaKu3SlFmzQRFIkID5VzGjYt4mh+KaI+336B2aOtEXlIplhjyFzSqhh3v3FNT/8vHo4bYQZW+oQeZdlBBHzw=
