language: node_js
node_js:
- '10'
script: npm run build
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master
env:
  global:
    secure: B/kAR3WipDwSJYxAkrX3aBPkpEpeLBdbGXYKY478XBdsPyY16dMnyShWDLCOpniE7iQYXSvaBLLjZHaKsm9ZqHnvSGP3+MrxTjnj4Dus7fV/S3l7virj/fsorZoERpAE7E/KBoPjmU0+cB5szElM4sHxchBh+H9fNg7ap/NWUuM=
