name: CI & CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-test-ny:
    name: Unit Test NY TZ
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Change timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/New_York

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: Unit test
        run: npm t

  unit-test:
    name: Unit Test
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: Unit test
        run: npm t

  deploy-dev:
    name: Deploy to Cloudflare Pages - Dev
    needs: [unit-test-ny, unit-test]
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip-ci]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build -- --base /
        env:
          VITE_LISTS_URL: ${{ secrets.VITE_LISTS_URL_DEV }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=ledge-dev

  deploy-prod:
    name: Deploy to Cloudflare Pages - Prod
    needs: [unit-test-ny, unit-test]
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[skip-ci]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build -- --base /
        env:
          VITE_LISTS_URL: ${{ secrets.VITE_LISTS_URL_PROD }}

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=ledge
