name: Deploy to GH Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        env:
          SERVER_URL: https://ledge.cloud.tridnguyen.com
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email "deploy@tridnguyen.com"
          git add -f dist
          git commit --no-verify -m "Update from commit $GITHUB_SHA"
          git subtree push --prefix dist origin gh-pages

