name: Production Test

on:
  workflow_dispatch:
  schedule:
    # run test every 2 hours
    - cron: "0 */2 * * *"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install deps
        run: npm install

      - name: Build
        env:
          SERVER_URL: https://api.tridnguyen.com/lists/ledge/tri
        run: npm run build

      - name: Cypress
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_AUTH0_DOMAIN: "tridnguyen.auth0.com"
          CYPRESS_AUTH0_CLIENT_ID: ${{ secrets.CYPRESS_AUTH0_CLIENT_ID }}
          CYPRESS_AUTH0_CLIENT_SECRET: ${{ secrets.CYPRESS_AUTH0_CLIENT_SECRET }}
          CYPRESS_BASE_URL: "https://tridnguyen.com/ledge"
          CYPRESS_SERVER_URL: "https://lists.cloud.tridnguyen.com/ledge/tri"
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          browser: chrome
          headless: true
